# I confirm that the attached is my own work #

# CODES - my.norm, my.chisq, my.rf


my.rnorm<-function(n,mean=0,sd=1){
  
  # Purpose: 
  #   A function which generates a vector of pseudo-random values from a normal distribution.
  #   The number of observations, mean and standard deviation can be specified in the argument of the function.
  # 
  # Inputs:
  #   n - number of observations, an integer >0
  #   mean - normal distribution with mean = mean, default value = 0
  #   sd - normal distribution with standard deviation = sd, defult value = 1
  #
  # Outputs:
  #   norm.val - the vector of pseudo-random values of length = n
  
  if((n%%1==0)=="TRUE" & length(n)==1 & n>0 & sd>=0){ 
    # Error trapping on inputs:
    # check n is a scalar and a positive integer and that sd is non-negative
    
    norm.val<-numeric(n) 
    # object norm.val is an empty vector of length = n
    
    for(i in 1:n){
      # for loop from 1 to n
      
      u<-runif(16)
      # assign 16 random deviates from a Uniform distribution with upper limit = 1, lower limit=0 to object u
      
      x<-((sum(u)-8)*sqrt(12/16)*sd+mean) 
      # generate a value from a Normal distribution using object u by the Central Limit Theorem method
      
      norm.val[i]<-x
      # for each i store the outcome x in the vector norm.val
    }
    return(norm.val)
    # return the output norm.val
  }else{
    stop("invalid argument")
    #if the function detects an incorrect input, stop the function running and print "invalid argument"
  }
}




my.rchisq<-function(n,df=1){
  
  # Purpose: 
  #   A function which generates a vector of pseudo-random values from a chi-squared distribution.
  #   The number of observations and degrees of freedom can be specified in the argument of the function.
  # 
  # Inputs:
  #   n - number of observations, an integer >0
  #   df - chi-squared distribution with degrees of freedom = df, defult value = 1
  #
  # Outputs:
  #   chi.val - the vector of pseudo-random values of length = n
  
  if(n%%1==0 & n>0 & df%%1==0 & df>0){
    # Error trapping on inputs: 
    # check n is a scalar and a strictly positive integer and that df is non-negative
    
    chi.val<-numeric(n)
    # object chi.val is an empty vector of length = n
    
    for(j in 1:n){
      # for loop which runs from 1 to n
      
      v<-my.rnorm(df)
      # v is a vector of values from a standard normal distribution, generated by the function my.norm(df,0,1)
      
      z<-sum(v^2)
      # z is the object which stores the sum of the squared pseudo-random standard normal values
      
      chi.val[j]<-z
      # for each j store the outcome z in the vector chi.val
    }
    return(chi.val)
    # return the output chi.val
    
  }else{
    stop("invalid argument")
    # if the function detects an incorrect input, stop the function running and print "invalid argument"
  }
}




my.rf<-function(n,df1=1,df2=1){
  
  # Purpose: 
  #   A function which generates a vector of pseudo-random values from an F distribution.
  #   The number of observations and degrees of freedom can be specified in the argument of the function.
  # 
  # Inputs:
  #   n - number of observations, a positive integer  greater than 0
  #   df1, df2 - F distribution with df1 and df2 degrees of freedom, df1 and df2 defult values = 1
  #
  # Outputs:
  #   f.val - the vector of pseudo-random values of length = n
  
  if((n%%1==0 & n>0 & df1%%1==0 & df2%%1==0 & df1>0 & df2>0)=="TRUE"){
    # Error trapping on inputs: 
    # check n is a scalar and a strictly positive integer and df1 & df2 are non-negative integers
    
    f.val<-numeric(n)
    # object f.val is an empty vector of length = n
    
    for (k in 1:n){
      # for loop which runs from 1 to n
      
      U<-sum(my.rchisq(n,df1))
      V<-sum(my.rchisq(n,df2))
      # objects U & V are the sum of n & m chi-squared pseudo-random values on df1 & df2 degrees of freedom respectively
      
      f<-(U/df1)/(V/df2)
      # f stores the pseudo-random value from an F distribution generated each loop
      
      f.val[k]<-f
      # each value of f is stored in f.val, f.val is a vector of length = n 
    }
    return(f.val)
    # return the output f.val
  }else{
    stop("invalid argument")
    # if the function detects an incorrect input, stop the function running and print "invalid argument"
  }
}




# Testing my code


test.is.norm<-function(n,mean=0,sd=1){{
  
  # Purpose: test to ensure that the pseudo-random values are from a normal distribution
  # (by looking at the graphs and plots and the result of the KS test)
  # Inputs:
  #   n - number of observations
  #   mean - mean
  #   sd - standard deviation
  # Outputs:
  #   3 graphs: histogram, boxplot and qq plot
  #   results of a Kolmogorov–Smirnov Test with H0:values are from a Normal Distribution vs the alterative
  #   summary of results
  
  x<-my.norm(n,mean,sd)
  old.par<-par("mfrow")
  par(mfrow=c(1,3))
  on.exit(par(mfrow=old.par))
  hist(x,probability=TRUE)
  lines(density(x))
  boxplot(x,horizontal=TRUE)
  rug(x)
  qqnorm(x)
  ks.test(x,"pnorm",0,1,alternative="two.sided")
}
if("p-value">0.1){
  cat("The Kolmogorov–Smirnov Test gives no evidence against Ho: the values are from a normal distribution \n")
}
return(summary(x))
}





test.is.chisq<-function(n,df=1){
  
  # Purpose: testing if values given by my.chisq are from a chi-squared distribution by looking at mean/variance
  #          Mean/Variance ratio of chi-squared is 0.5, so my.chisq should get this result approximately
  # Inputs:
  #   n - number of observations
  #   df - degrees of freedom
  # Outputs:
  #   Cat statement and value of mean/variance from my.chisq
  
  x<-my.chisq(n,df)
  x2<-mean(x)/var(x)
  if(0.4<=x2 & x2<=0.6){
    cat("the pseudo-random values are from a chi-squared distribution\n","mean-variance ratio is\n",x2)
  }else{
    cat("the pseudo-random values are not necessarily from a chi-squared distribution, try a larger value of n\n",
        "mean-variance ratio is\n",x2)
  }
}




test.deft.len<-function(n){
  
  # Purpose: test checks when only n is an input argument, my.norm, my.chisq & my.rf return vectors
  #          of length = n and checks that default input values are in place
  # Inputs:
  #   n - number of observations
  # Outputs:
  #   Length of the vector my.norm, my.chisq and my.rf produce
  #   Cat statement
  
  x<-my.norm(n)
  y<-my.chisq(n)
  z<-my.chisq(n)
  if(is.numeric(x)=="TRUE" & is.numeric(y)=="TRUE" & is.numeric(z)=="TRUE"){
    cat("length(my.norm) =",length(x),"\n length(my.chisq) =",length(y),"\n length(my.rf) =",length(z),
        "\n default arguements are in place")
  }
}


test.nninteger<-function(n,sd,df,df1,df2){
  
# Purpose: testing error trappings
#          n, df, df1 and df2 should be input arguments which are non-negative integers
#          sd should be a non-neative value
#          here mean = 0 (my.norm)
# Inputs:
#   n - number of observations
#   sd - standard deviation (my.norm)
#   df - degrees of freedom (my.chisq)
#   df1 - degrees of freedom 1 (my.rf)
#   df2 - degrees of freedom 2 (my.rf)
# Outputs:
#   Cat statement

  values<-c(my.norm(n,0,sd),my.chisq(n,df),my.rf(n,df1,df2))
  pass.test<-is.numeric(values)
  if((pass.test)=="TRUE"){
    cat(n,df,df1,df2,"- all of these values are non-negative integers\n",sd,"- this value is non-negative\n")
  }
}


