# I confirm that the attached is my own work, except where clearly indicated in
# the text.

my.rnorm <- function(n,mean=0,sd=1){
# Purpose: Generates pseudo-random normal deviates from random uniform deviates
# Inputs: n - a numeric scalar of the number of deviates to generate
# mean - mean of values to return (default 0)
# sd - standard deviation of values to return (default 1)  
# Outputs: normdev - a numeric vector of n random normal deviates
  if(n<=0|sd<0) stop("invalid arguments")
  # stops function execution if n is less than or equal to 0 or sd is less than 0
  if(n-floor(n)!=0) stop("invalid arguments")
  # stops function execution if n is non-integer
  normdev <- vector(length=n)
  for(i in 1:n){
    x <- runif(16)
    normdev[i] <- ((sum(x)-8)*sqrt(12/16))*sd+mean
    # generates 16 random uniformly distributed deviates and uses the central 
    # limit theorem method to produce a single normally-distributed deviate, 
    # n times
  }
  return(normdev)
}

my.rchisq <- function(n,df=1){
# Purpose: Generates pseudo-random chi-squared deviates from random normal 
# deviates
# Inputs: n - a numeric scalar of the number of deviates to generate
# df - degrees of freedom of the distribution (default 1)
# Outputs: chidev - A numeric vector of n random chi-squared deviates
  if(n<=0|df<=0) stop("invalid arguments")
  # stops function execution if n or df are less than or equal to 0
  if(n-floor(n)!=0) stop("invalid arguments")
  if(df-floor(df)!=0) stop("invalid arguments")
  # stops function execution if n, df are non-integer
  chidev <- vector(length=n)
  for(i in 1:n){
    y <- my.rnorm(df)
    chidev[i] <- sum(y^2)
    # generates df normal deviates and squares these to give chi-squared 
    # deviates, n times
  }
  return(chidev)
}

my.rf <- function(n,df1=1,df2=1){
# Purpose: Generates n pseudo-random numbers with an F-distribution from 
# chi-squared deviates 
# Inputs: n - a numeric scalar
# df1 - degrees of freedom of the numerator (default 1)
# df2 - degrees of freedom of the denominator (default 1) 
# Outputs: fdev - a numeric vector of n random F-distributed deviates  
  if(n<=0) stop("invalid arguments")
  if(n-floor(n)!=0) stop("invalid arguments")
  if(df1<=0|df2<=0) stop("invalid arguments")
  if(df1-floor(df1)!=0) stop("invalid arguments")
  if(df2-floor(df2)!=0) stop("invalid arguments")
  # stops function execution if n, df1, df2 are less than or equal to 0 or are
  # non-integer
  fdev <- vector(length=n)
  for(i in 1:n){
    u <- my.rchisq(df1)
    v <- my.rchisq(df2)
    fdev[i] <- (u/df1)/(v/df2)
    # generates df1 and df2 chi-squared deviates from which F-distributed are 
    # then generated
  }
  return(fdev)
}

my.test1 <- function(n){
# Purpose: An informal test to check if the deviates generated by the my.rnorm 
# function are approximately normally distributed
# Inputs: n - a numeric scalar of the number of deviates to generate
# Outputs: A qqnorm plot of the generated deviates; if the plot is approximately 
# linear the deviates can be assumed to be normal  
  if(n<100) stop("need a larger value of n!")
  # stops function if value of n is small as test would not be very informative
  qqnorm(my.rnorm(n))
}

my.test2 <- function(){
# Purpose: Error check for my.rnorm function for values of n between 4 and -3
# Inputs: none
# Outputs: values of n and pass/fail depending on whether a numeric vector was 
# returned 
  for (n in seq(4,-3,-1)){
    x <- try(my.rnorm(n),silent=TRUE)
    # generates normal deviates, suppressing any error messages
    if (is.numeric(x)){
      cat("number of deviates =",n,"pass","\n")
    } else {
      cat("number of deviates =",n,"fail","\n") 
    }
  }
}  

my.test3 <- function(n,df1,df2){
# Purpose: Error check for my.rf function
# Inputs: n - a numeric scalar
# df1 - degrees of freedom of numerator
# df2 - degrees of freedom of denominator 
# Outputs: pass/fail depending on whether a numeric vector was returned 
  x <- try(my.rf(n,df1,df2),silent=TRUE)
  # generates F-distributed deviates, suppressing any error messages
  if (is.numeric(x)){
    cat("pass")
  } else {
    cat("fail")
  }
}

  