#I confirm that the attached is my own work, except where clearly indicated in the text.

my.rnorm <- function(n,mean=0,sd=1) {
  my.mean <- mean; my.sd <- sd
  # the purpose of this function is to generate randomly normally distributed deviates
  # from the specified algorithm
  if (missing(n)) stop ("Please enter n")
  # If user tries to run the function without entering parameter n (number of deviates)
  # The function will stop and show an error with a message asking to enter n
  if (length(n)!=1 | length(my.mean)!=1 | length(my.sd)!=1) stop ("Entered parameteres cannot be vectors or matrixes")
  #checks whether entered parameters are scalars
  if (!is.numeric(n)) stop ("Please ensure n is a numeric parameter")
  # If parametre n is not a number the function will be stopped with a message
  # asking a user to ensure that entered parameter is numeric
  if (n%%1!=0 | n < 1) stop ("Please ensure n is an integer and >=1")
  # checks whether parameter is a whole and positive number
  if (!is.numeric(my.mean) | !is.numeric(my.sd) | my.sd<0) stop ("Please ensure that both entered mean and st. deviation parameters are numeric and sd. deviation is positive")
  # checks whether entered parameters for mean and st. deviation are numeric, 
  # and whether my.sd is positive
  X <- numeric(n)
  for (i in 1:n) { #this for loop generates random noramally distributed deviates
    # by using given algorithm
    random.number <- runif(16,0,1)
    X[i]<-((sum(random.number)-8)*(12/16)^0.5)} #the algorithm that generates normally-distributes deviates 
    X <- X*my.sd+my.mean #transforms our results into values with mean equal my.mean and st. deviatioin equal my.sd
  return (X)} #returns vector X which elements are pseudo-random values from a norm distribution using given algorithm

my.rchisq <- function(n,df=1) {
  my.df <- df
  #the purpose of this function is to generate vector which elements are random chi square deviates generated by 
  #my.rnorm function with degree of freedom my.df
  if (missing(n)) stop ("Please enter n") #ensures that user has entered the parameter n
  if (length(n)!=1 | length(my.df)!=1) stop ("Entered parameteres cannot be vectors or matrixes")
  #checks whether entered parameters are scalars
  if (!is.numeric(n) | !is.numeric(my.df)) stop ("Please ensure that entered parameters are numeric!")
  # ensures that both entered parameters n and degree of freedom are numbers 
  if (n%%1!=0 | n < 1) stop ("Please ensure n is an integer and >=1")
  # ensures that n is a positive integer
  if (my.df%%1!=0 | my.df < 1) stop ("Please ensure my.df is an integer and >=1")
  # ensures that my.df is a positive integer
  Y <- numeric(n) # assigning vector where we store chi square generated elements 
  for (i in 1:n) { #this loop generates elements of our vector with chi square elements
    X <- my.rnorm (my.df) # my.rnorm function generates normally distributed deviates
    Y[i] <- sum(X^2)} # each element is squared and summed, and added to our vector Y 
  return(Y)}


my.rf <- function(n,df1=1,df2=1) {
  my.df1 <- df1; my.df2 <- df2
  #this function generates vector with F-distributed deviates
  #elements of the vector are generated by my.chisq function with degrees of freedom my.df1 and my.df2
  if (missing(n)) stop ("Please enter n") #stop running the function if length of the vector is not entered
  if (length(n)!=1 | length(my.df1)!=1 | length(my.df2)!=1) stop ("Entered parameteres cannot be vectors or matrixes")
  #checks whether entered parameters are scalars
  if (!is.numeric(n) | !is.numeric(my.df1) | !is.numeric(my.df2)) stop ("Please ensure that entered parameters are positive integers!")
  # stops the function if entered length of the vector n, or degrees of freedom are non numeric 
  if (n%%1!=0 | n < 1) stop ("Please ensure n is an integer and >=1")
  #stops the function if length of the vector (n) is not a positive integer 
  if (my.df1%%1!=0 | my.df1 < 1 | my.df2%%1!=0 | my.df2 < 1) stop ("Please ensure that entered degrees of freedom are integesr and >=1")
  #stops the function if any of two entered degrees of freedom are not whole positive numbers 
  rf <-numeric(n)
  U <-numeric(n)
  V <-numeric(n)
  for (i in 1:n) { #this loop generates denominator and nominator of F distribution
    # by using my.chisq function with two different degrees of freedom
    U[i]<-my.rchisq(1,my.df1)
    V[i]<-my.rchisq(1,my.df2)
    rf[i]<-(U[i]/my.df1)/(V[i]/my.df2)}
  return(rf)} #returns numeric vector rf with n F-distributed elements



mytest.myrnorm <-function(n,x=0,y=1) {
  # this very simple function tests the difference between the input mean and st deviation
  # and the mean and st deviation we calculated for our set generated by my.rnorm 
  # the function doesn't test the code but it shows how closely were generated your 
  # random variates to inputted mean (x) and sd (y) 
  p<-my.rnorm (n,x,y)
  x_check<-mean(p)
  y_check<-sd(p)
  mean_error<-abs(x-x_check) #calcualtes absolute difference between input mean and mean for our generated set
  mean_sd<-abs(y-y_check) #calculates absolute difference between input st deviation and st deviation of the generated set
  cat (mean_error,mean_sd)
}

